/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author malico
 */
public class VistaVentasPorArticulo extends javax.swing.JDialog {

    /**
     * Creates new form VistaSuma
     */
    public VistaVentasPorArticulo() {
        initComponents();
        continuarInicializandoComponentes();
    }
    
    public void setFecha(String etFecha) {
        this.etFecha.setText(etFecha);
    }
    
    public void setHora(String etHora) {
        this.etHora.setText(etHora);
    }
    
    public void agregarFilaTablaVentas(String articulo, 
            Integer cantidad, Double importe) {
        String col1 = "  " + articulo;
        String col2 = cantidad.toString() + "  ";
        String col3 = importe.toString() + "  ";
        javax.swing.table.DefaultTableModel modeloTablaDetalle =
                (javax.swing.table.DefaultTableModel) tablaDetalle.getModel();
        String[] datos = {col1, col2, col3};
        modeloTablaDetalle.addRow(datos);
    }

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etHora = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btRetornar = new java.awt.Button();
        btConfirmar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas por Artículo");
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(858, 580));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encabezado"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Ventas por Artículo");
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 17));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Fecha");
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 17));
        jPanel1.add(jLabel2);

        etFecha.setEditable(false);
        etFecha.setBackground(new java.awt.Color(255, 255, 102));
        etFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etFecha.setFocusable(false);
        etFecha.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(etFecha);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Hora");
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 17));
        jPanel1.add(jLabel3);

        etHora.setEditable(false);
        etHora.setBackground(new java.awt.Color(255, 255, 102));
        etHora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        etHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etHora.setFocusable(false);
        etHora.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(etHora);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));
        jPanel8.setPreferredSize(new java.awt.Dimension(822, 390));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 400));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículo", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalle.setFocusable(false);
        tablaDetalle.setRowHeight(20);
        jScrollPane2.setViewportView(tablaDetalle);

        jPanel8.add(jScrollPane2);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btRetornar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btRetornar.setLabel("Retornar");
        jPanel3.add(btRetornar);

        btConfirmar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btConfirmar.setLabel("Confirmar");
        jPanel3.add(btConfirmar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btConfirmar;
    public java.awt.Button btRetornar;
    private javax.swing.JTextField etFecha;
    private javax.swing.JTextField etHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables

    private void continuarInicializandoComponentes() {
        javax.swing.table.TableColumn columna1 = tablaDetalle.getColumn("Artículo");
        columna1.setPreferredWidth(300); 
        DefaultTableCellRenderer tcrr = new DefaultTableCellRenderer();
        tcrr.setHorizontalAlignment(SwingConstants.RIGHT);
        tablaDetalle.getColumnModel().getColumn(1).setCellRenderer(tcrr);
        tablaDetalle.getColumnModel().getColumn(2).setCellRenderer(tcrr);
    }
}
