/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author malico
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        movimientos = new javax.swing.JMenu();
        ingresarFactura = new javax.swing.JMenuItem();
        ingresarRecibo = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        consultarFactura = new javax.swing.JMenuItem();
        consultarRecibo = new javax.swing.JMenuItem();
        consultarMovimientosPorCliente = new javax.swing.JMenuItem();
        estadisticas = new javax.swing.JMenu();
        totalesPorCliente = new javax.swing.JMenuItem();
        ventasPorArticulo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modelos MVC DAO DTO SINGLETON");
        setBounds(new java.awt.Rectangle(50, 50, 800, 600));
        setPreferredSize(new java.awt.Dimension(858, 585));

        jMenu1.setText("Archivo");

        login.setText("Login");
        jMenu1.add(login);

        logout.setText("Logout");
        logout.setEnabled(false);
        jMenu1.add(logout);
        jMenu1.add(jSeparator1);

        salir.setText("Salir");
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        movimientos.setText("Movimientos");
        movimientos.setEnabled(false);

        ingresarFactura.setText("Ingresar Factura");
        movimientos.add(ingresarFactura);

        ingresarRecibo.setText("Ingresar Recibo");
        movimientos.add(ingresarRecibo);

        jMenuBar1.add(movimientos);

        consultas.setText("Consultas");
        consultas.setEnabled(false);

        consultarFactura.setText("Consultar Factura");
        consultas.add(consultarFactura);

        consultarRecibo.setText("Consultar Recibo");
        consultarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarReciboActionPerformed(evt);
            }
        });
        consultas.add(consultarRecibo);

        consultarMovimientosPorCliente.setText("Movimientos por Cliente");
        consultas.add(consultarMovimientosPorCliente);

        jMenuBar1.add(consultas);

        estadisticas.setText("Estadísticas");
        estadisticas.setEnabled(false);

        totalesPorCliente.setText("Totales por Cliente");
        estadisticas.add(totalesPorCliente);

        ventasPorArticulo.setText("Ventas por Artículo");
        estadisticas.add(ventasPorArticulo);

        jMenuBar1.add(estadisticas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarReciboActionPerformed

    private void ingresarFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarFactura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarFactura1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem consultarFactura;
    public javax.swing.JMenuItem consultarMovimientosPorCliente;
    public javax.swing.JMenuItem consultarRecibo;
    public javax.swing.JMenu consultas;
    public javax.swing.JMenu estadisticas;
    public javax.swing.JMenuItem ingresarFactura;
    public javax.swing.JMenuItem ingresarRecibo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JMenuItem login;
    public javax.swing.JMenuItem logout;
    public javax.swing.JMenu movimientos;
    public javax.swing.JMenuItem salir;
    public javax.swing.JMenuItem totalesPorCliente;
    public javax.swing.JMenuItem ventasPorArticulo;
    // End of variables declaration//GEN-END:variables
}
